language: python
python:
  - "2.7"
# command to install dependencies
install:
  - pip install -r source/requirements.txt
# command to run tests
script:
  - export PYTHONPATH=./source
  - pytest # or py.test for Python versions 3.5 and below
